### ISSUE TITLE
[aws-azure-login@3.6.3] Login issue

### ISSUE THREAD

**Issue by nikbarseghyan** [kennethaasan/aws-azure-login#328]
**Steps to Reproduce**
1. Update `aws-azure-login` to version 3.6.3
2. Authenticate(microsoft) using the library

**Expected Behavior**
I expect the authentication process to complete without any errors after updating to the latest version of `aws-azure-login`.

**Actual Behavior**
I'm getting the TypeError related to the `proxy_agent_1.default` function.
`
TypeError: (0 , proxy_agent_1.default) is not a function
    at Object._assumeRoleAsync (C:\Users\.npm-packages\node_modules\aws-azure-login\lib\login.js:773:59)
    at Object.loginAsync (C:\Users\.npm-packages\node_modules\aws-azure-login\lib\login.js:381:20)      
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

Can someone help me resolve this issue😊? 
I'd appreciate any guidance or suggestions on how to fix this problem.

**Comment by AlexWang-16** [comment]
Please [see this comment](https://github.com/aws-azure-login/aws-azure-login/issues/322#issuecomment-2059284425). It's not an ideal solution, but it works until dev team is able to address this issue.

I believe the issue is coming from a version upgrade for the http_proxy_agent package. This caused the old API call to fail. The solution is to instantiate a new instance https proxy agent to work around the issue.

**Comment by nikbarseghyan** [comment]
Good thanks for the information
I downgraded to v3.6.1 and it works.
